# Site settings
title: Resume
description: Resume Portfolio
favicon: /iCard/assets/img/resume3.jpg
baseurl: http://skanda-shastry.github.io/iCard
url: http://skanda-shastry.github.io/iCard
rss_url: /iCard-Resume/pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Skanda Shastry
  title: Product Developer
  address: Bangalore, Karnataka
  email: skanda.shastry02@gmail.com
  link: http://skanda-shastry.github.io/
  weibo:
  github: skanda-shastry
  linkedin: skandashastry02
  twitter: skanda_ms
  gavatar: /iCard/assets/img/skanda1.jpg
  workHistory:
    - work1:
      company: Exceleron Software Pvt Ltd
      location: Bangalore, Karnataka
      title: Associate Product Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Viamagus Technologies
      location: Bangalore, Karnataka
      title: Software Development Intern
      started: 2013
      duration: (2013 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: JNNCE Shimoga
      degree: Bachelor
      major: ComputerScience Engineering
      started: 2009
      duration: (2009 - 2013)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Kannada
      proficiency: Native

  programmingSkills:
    - skill1:
      name: Perl
      percentage: 80%
    - skill2:
      name: HTML
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 60%
    - skill5:
      name: SQL
      percentage: 75%
