# Site settings
title: Skanda Shastry Resume 
description:  My Girlfriend Hates This Blog
favicon: /iCard/assets/img/resume3.jpg
baseurl: http://skanda-shastry.github.io/iCard
url: http://skanda-shastry.github.io/iCard
rss_url: /iCard-Resume/pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Skanda Shastry
  title: Product Solution Engineer
  address: Bangalore, Karnataka
  email: skanda.shastry02@gmail.com
  link: http://skanda-shastry.github.io/iCard
  weibo:
  github: skanda-shastry
  linkedin: skandashastry02
  twitter: skanda_ms
  gavatar: ../assets/skanda.jpg
  workHistory:
    - work1:
      company: Flipkart Internet India Pvt Ltd
      location: Bangalore, Karnataka
      title: Product Solution Engineer
      started: 2016
      duration: (2016 - Present)
      description: >
             * Build,deploying,automating,maintaining & managing cloud based production services to ensure the availability, performance, scalability of the system. <br/>
             * Hands on experience in Relational databases,backup, disaster recovery, DBA best practices & data modeling.<br/>
             * Setup up an system Infrastructure, alerts, fault detection,identifies anomalies & system health, Capacity planning,load balancing <br/>
             * Proficient problem solving, troubleshooting,transform the Planning & Accounting business requirement into tech feasibility. majorly on Disbursement,Invoice generation,tax computation,Supply Planning,Demand Forecasting. <br/>
    - work2:
      company: Exceleron Software Pvt Ltd
      location: Bangalore, Karnataka
      title: Product Developer
      started: 2014
      duration: (2014 - 2015)
      description: >
             * Prev worked as a developer in design & development of Meter Data Management    <br/>                                                                                                                                                                                                                                                        
             * Extensive working knowledge in the Energy / Utilities domain. ( Meter Data Management, Smart Grid, Smart Metering, AMI, CIS, Asset Management ) <br/>
             * Provide an technical support engineer for "MyUsage™ prepaid alert management system".
    - work3:
      company: Viamagus Technologies
      location: Bangalore, Karnataka
      title: Software Development Intern
      started: 2013
      duration: (2013 - 2014)
      description: >
            * Proficent on UI and Frontend Design and Development.(Responsive /adaptive). <br/>
            * Working knowledge on frontend framework like Jquery & Backbone.js. <br/>
            * Write testcase, assist in debugging,and testing the application.
  educationHistory:
    - education1:
      organization: JNNCE Shimoga
      degree: Bachelor
      major: ComputerScience Engineering
      started: 2013
      duration: (2009 - 2013)
      description: >
                  In 2013 I graduated from Jawaharlal Nehru National College of Engineering (JNNCE) Shimoga with a B.E. in Computer Science. <br/>
                   Throughout college I was an active member of Computer Science Club,  I learned a ton while I was there, both through personal projects and just being in an atmosphere of learning and (more importantly) doing.
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Kannada
      proficiency: Native
      
  hobbies:
    - hobbies1:
      name: Reading
    - hobbies2:
      name: Table Tennis
    - hobbies3:
      name: Blogging
      
  programmingSkills:
    - skill1:
      name: "Python/ShellScripting"
      percentage: 80%
    - skill2:
      name: "MySQL Hbase"
      percentage: 60%
    - skill3:
      name: "DevOps tool"
      percentage: 80%
    - skill4:
      name: HTML/CSS Javascript Webservice
      percentage: 50%
   
